name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - dev
      - qa
      - stage
  pull_request:
    branches:
      - main
      - dev
      - qa
      - stage

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Install dependencies
      run: npm install

    - name: Run tests
      run: npm test

    - name: Build application
      run: npm run build

    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: build
        path: build/

    - name: Send notification on failure
      if: failure()
      uses: dawidd6/action-send-mail@v3
      with:
        server_address: smtp.sendgrid.net
        server_port: 587
        username: apikey
        password: ${{ secrets.SENDGRID_API_KEY }}
        subject: GitHub Actions Workflow Failed
        body: Build job has failed. Please check the logs for details.
        from: ${{ secrets.SENDGRID_FROM_EMAIL }}
        to: ${{ secrets.SENDGRID_TO_EMAIL }}

  deploy_dev:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/dev'

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Download build artifacts
      uses: actions/download-artifact@v3
      with:
        name: build
        path: build/

    - name: Deploy to Dev
      env:
        SSH_PRIVATE_KEY: ${{ secrets.DEV_SSH_PRIVATE_KEY }}
        SSH_HOST: ${{ secrets.DEV_SSH_HOST }}
        SSH_USERNAME: ${{ secrets.DEV_SSH_USERNAME }}
      run: |
        echo "${SSH_PRIVATE_KEY}" > private_key
        chmod 600 private_key
        rsync -avz -e "ssh -i private_key" build/ ${SSH_USERNAME}@${SSH_HOST}:/var/www/dev_myapp

    - name: Clean up
      run: rm private_key

    - name: Send notification on failure
      if: failure()
      uses: dawidd6/action-send-mail@v3
      with:
        server_address: smtp.sendgrid.net
        server_port: 587
        username: apikey
        password: ${{ secrets.SENDGRID_API_KEY }}
        subject: Deployment to Dev Failed
        body: Deployment to Dev has failed. Please check the logs for details.
        from: ${{ secrets.SENDGRID_FROM_EMAIL }}
        to: ${{ secrets.SENDGRID_TO_EMAIL }}

  deploy_qa:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/qa'

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Download build artifacts
      uses: actions/download-artifact@v3
      with:
        name: build
        path: build/

    - name: Deploy to QA
      env:
        SSH_PRIVATE_KEY: ${{ secrets.QA_SSH_PRIVATE_KEY }}
        SSH_HOST: ${{ secrets.QA_SSH_HOST }}
        SSH_USERNAME: ${{ secrets.QA_SSH_USERNAME }}
      run: |
        echo "${SSH_PRIVATE_KEY}" > private_key
        chmod 600 private_key
        rsync -avz -e "ssh -i private_key" build/ ${SSH_USERNAME}@${SSH_HOST}:/var/www/qa_myapp

    - name: Clean up
      run: rm private_key

    - name: Send notification on failure
      if: failure()
      uses: dawidd6/action-send-mail@v3
      with:
        server_address: smtp.sendgrid.net
        server_port: 587
        username: apikey
        password: ${{ secrets.SENDGRID_API_KEY }}
        subject: Deployment to QA Failed
        body: Deployment to QA has failed. Please check the logs for details.
        from: ${{ secrets.SENDGRID_FROM_EMAIL }}
        to: ${{ secrets.SENDGRID_TO_EMAIL }}

  deploy_stage:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/stage'

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Download build artifacts
      uses: actions/download-artifact@v3
      with:
        name: build
        path: build/

    - name: Deploy to Stage
      env:
        SSH_PRIVATE_KEY: ${{ secrets.STAGE_SSH_PRIVATE_KEY }}
        SSH_HOST: ${{ secrets.STAGE_SSH_HOST }}
        SSH_USERNAME: ${{ secrets.STAGE_SSH_USERNAME }}
      run: |
        echo "${SSH_PRIVATE_KEY}" > private_key
        chmod 600 private_key
        rsync -avz -e "ssh -i private_key" build/ ${SSH_USERNAME}@${SSH_HOST}:/var/www/stage_myapp

    - name: Clean up
      run: rm private_key

    - name: Send notification on failure
      if: failure()
      uses: dawidd6/action-send-mail@v3
      with:
        server_address: smtp.sendgrid.net
        server_port: 587
        username: apikey
        password: ${{ secrets.SENDGRID_API_KEY }}
        subject: Deployment to Stage Failed
        body: Deployment to Stage has failed. Please check the logs for details.
        from: ${{ secrets.SENDGRID_FROM_EMAIL }}
        to: ${{ secrets.SENDGRID_TO_EMAIL }}

  deploy_prod:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main'

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Download build artifacts
      uses: actions/download-artifact@v3
      with:
        name: build
        path: build/

    - name: Deploy to Prod
      env:
        SSH_PRIVATE_KEY: ${{ secrets.PROD_SSH_PRIVATE_KEY }}
        SSH_HOST:
